"""Initial migration

Revision ID: 1e25a0bfd612
Revises: 
Create Date: 2024-09-30 14:35:56.219844

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1e25a0bfd612"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
