"""Ajust is_superuser default column to User model

Revision ID: 5980dce820c0
Revises: 79a61c852b39
Create Date: 2024-10-02 16:19:13.797270

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5980dce820c0"
down_revision: Union[str, None] = "79a61c852b39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
