"""Ajust is_superuser column to User model

Revision ID: 79a61c852b39
Revises: 
Create Date: 2024-10-02 16:18:28.458852

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "79a61c852b39"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
